# tool: [httpYac](https://httpyac.github.io/)

@base_url=http://localhost:8080
@cdevents_spec_examples=../cdevents-spec/examples

###
GET {{base_url}}/readyz

###
POST {{base_url}}/cdevents
headers:
#  ce-spec-version: 1.0
#  ce-id: 1234
#  ce-source: /mycontext
Content-Type: application/json

< service_deployed.json
